<img src="media/coco-banner.jpg">

# Welcome to learning Python!

These notebooks contain a mix of text and code. 
This makes it easy to experiment with code and keep documentation like this in the same place. 
You can execute each cell individually, and therefore work incrementally with your code. 

If you want to execute a cell, you can press the `►` button above when you have highlighted the cell. 
Alternatively, you can hit `Shift + Enter` to execute and progress to next cell or alternatively `Ctrl + Enter` (Windows) or `Cmd + Enter` (Mac). 
_Take your time to experiment with it if you like and don't hesitate to ask or search for things in your favorite browser._

----

Estos notebooks contienen una combinación de texto y código, lo que facilita la experimentación con el código y mantiene una documentación como esta en el mismo lugar. 
En los notebooks se puede ejecutar cada celda individualmente y, por lo tanto, trabajar de forma incremental con tu código. 

Si deseas ejecutar una celda, puedes presionar el botón `►` de arriba cuando se haya resaltado la celda o presionar `Shift + Enter` para ejecutar y avanzar a la siguiente celda. Puedes usar alternativamente `Ctrl + Enter` (Windows) o `Cmd + Enter` (Mac).
_Tómate tu tiempo para experimentar con él si quieres y no dudes en preguntar o buscar cosas en tu navegador favorito._

## Introduction to Python | Introducción a Python


**In this notebook we will learn about | En este notebook aprenderemos sobre:**
* Variables | Variables
* Types of data | Tipo de datos
* Different data structures |  Diferentes estructuras de datos
* Working with NumPy arrays | Trabajar con NumPy arrays

### Variables and data type | Variables y tipos de datos 

A _variable_ allows us to store a value.
In Python, we can assign a value to a variable using the equals sign `=`.

----

Una _variable_ nos permite almacenar un valor en un lugar determinado. 
En Python usamos el símbolo `=` para asignar un valor a una variable.

In [1]:
alumni = 15

course_name = "CoCo"

The keyword `print()` is a function in Python. We can use it to see the value stored in the variable.

----

`print()` es una función en Python, que usamos para examinar el valor asignado a una variable.

In [2]:
print(alumni)

15


Moreover, variables can easily be updated. | Además, las variables se pueden actualizar fácilmente.

In [3]:
alumni = 35

print(alumni)

35


In [4]:
print(course_name, "course has", alumni, "alumni")

CoCo course has 35 alumni


**Data Types | Tipos de datos**

There are several different data types that we will be exploring in the course. | Hay diferentes tipos de datos que vamos a ver en el curso.

* integers (int): integer numbers | números enteros.
* strings (str): sequence of alphanumeric text or other symbols | cadena de caracteres.
* floats (float): representation of real numbers | valores de punto flotante (representación aproximada de números reales).


In [5]:
type(alumni)

int

In [6]:
type(course_name)

str

In [7]:
half_alumni = alumni / 2

print(half_alumni, "is", type(half_alumni))

17.5 is <class 'float'>


#### Formative assessment 1

What will be the output of the next cell? | ¿Cual será el output de la siguiente celda?

```python
channel = 100.
type(channel)
```

1. int

2. float

3. str

In [8]:
# Solution | Solución

channel = 100.
type(channel)

float

If you want to concatenate two or more strings, there are several ways to achieve this in Python. 
The simplest method is to use `+`

---

Si desea concatenar dos o más cadenas de caracteres hay varias formas de hacerlo.
La más común es usar `+`.

In [9]:
saludo = "hola" + " " + "mundo"

print(saludo)

hola mundo


#### Formative assessment 2

We have a file in the following path: `data/hawaii-profile.csv`. What will happen if we run the following code? 

---

Tenemos un archivo en el siguiente path: `data/hawaii-profile.csv` ¿Qué pasá si ejecutamos el siguiente código?

```python
path = data/hawaii-profile.csv
print(path)
```

1. Return an error | Devuelve un error

2. Return the value stored in the `path` variable as | Devuelve el valor alojado en la variable `path` como: `data/data.csv`

In [10]:
# Solution | Solución 

path = data/data.csv
print(path)

NameError: name 'data' is not defined

We define the variable path as an string, so we need to use ""

---

Estamso definiendo la variable path como una cadena de caracteres, por lo tanto debemos usar ""

In [11]:
# Correct answer | Respuesta correcta

path = "data/data.csv"
print(path)
print(type(path))

data/data.csv
<class 'str'>


### Mathematical operations | Operaciones matemáticas

All of the standard calculator arithmetic operations are available between variables.
We measure a certain geophysical variable at a height of 53.2 meters above sea level. 

---

Podemos aplicar diferentes operaciones aritméticas entre distintas variables.
Medimos una determinada variable geofísica a una altura de 53.2 metros sobre el nivel del mar.

In [10]:
sea_height = 53.2

In [11]:
sea_height

53.2

**Addition | Suma**

In [12]:
sea_height + 10.6

63.800000000000004

In [13]:
sea_height - 3.5

49.7

**Multiplication | Multiplicación**

In [14]:
sea_height * 2

106.4

**Division | División**

In [15]:
sea_height / 2

26.6

In [16]:
sea_height // 2

26.0

**Power | Potencia**

In [17]:
sea_height ** 2

2830.2400000000002

#### Formative Assessment 3

What values do the variables mass and age have after each of the following statements?

---

¿Qué valores tienen las variables masa y edad después de cada una de las siguientes afirmaciones?

```
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20

```
1. `mass = 47.5` and `age` does not exist

2. `mass = 47.5` and `age =  122` 

3. `mass = 95.0` and `age = 122`

4. `mass = 95.0` and `age = 102`

In [12]:
# Solution | Solución

mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20

print("mass:", mass, "age:", age)

mass: 95.0 age: 102


### Data Structures | Estructura de datos

A data structure is a term to describe a type of "data container". 
They are used to store multiples of variables and provide certain accessor functions to extract them from the container. 

---

Una estructura de datos es un término para describir un tipo de "contenedor de datos".
Se utilizan para almacenar múltiples variables y proporciona ciertas funciones de acceso para extraerlas del contenedor. 

#### Lists | Listas

Python lists are used to store a _collection of data_.
A list is composed of comma-separated values between square brackets.

---

Las listas nos permiten _guardar múltiples valores bajo una misma variable_.
Una lista es una lista de valores separados por comas entre corchetes.


In [31]:
impares = [1, 3, 5, 7, 9]

type(impares)

list

In [32]:
impares

[1, 3, 5, 7, 9]

Lists can store heterogeneous data, and you can even have lists of lists. | Las listas pueden contener datos heterogéneos (diferentes tipos de variables), hasta listas.

In [33]:
list_heterogeneous = ["agua", 20.1, 52]

print(list_heterogeneous)

['agua', 20.1, 52]


In [34]:
lista_anidadas = [[1, 2, 3], 3.0, "hielo"]

print(lista_anidadas)

[[1, 2, 3], 3.0, 'hielo']


Use the `append` function to add items to the end of a list. | Usamos la función `append` para agregar un elemento al final de la lista.

In [35]:
impares.append(11)

print(impares)

[1, 3, 5, 7, 9, 11]


#### Formative Assessment 4

We want to add two more element to the `impares` list, so, what will happen if we execute the following code?

---

Queremos agregar 2 elemento más a la lista `impares`. ¿Qué pasa si ejecutamos el siguiente código?: 

```python
impares = [1, 3, 5, 7, 9]
impares.append[[15, 17])
print(impares)
```

1. Return the `impares` list with the two new elements | Devuelve la lista `impares` con los 2 elementos nuevos:
```
[1, 3, 5, 7, 9, 11, 15, 17]
```

2. Return the `impares` list as a nested list, where the last element is a list | Devuelve la lista `impares` como una lista anidada donde el último elemento es una lista:
```
[1, 3, 5, 7, 9, 11, [15, 17]]
``` 

In [1]:
# Solution | Solución

impares = [1, 3, 5, 7, 9]
impares.append([15, 17])
print(impares)

[1, 3, 5, 7, 9, [15, 17]]


If we want to add more than one element to the list, we can't use the `append` function.
So, we must use the `extend` function or concatenate two lists using `+`

---

Si queremos agregar más de 1 elemento a una lista no podemos usar la función `append`.
Para eso debemos usar la función `extend` o concatenar listas usando `+`

In [37]:
impares.extend([19, 21])
impares

[1, 3, 5, 7, 9, [15, 17], 19, 21]

In [39]:
impares = impares + [23, 25] + [27]

impares

[1, 3, 5, 7, 9, [15, 17], 19, 21, 23, 25, 27]

We can access the values housed in a list through their indices. | Podemos acceder a los valores alojados dentro de una lista a través de sus índices.

In [48]:
temperaturas = [10.1, 14.6, 18.3, 20.3]

In [49]:
temperaturas

[10.1, 14.6, 18.3, 20.3]

In [50]:
temperaturas[0]

10.1

In [23]:
print("Primer valor de temperatura:", temperaturas[0])
print("Segundo valor de temperatura:", temperaturas[1])
print("Último valor de temperatura:", temperaturas[-1])
print("Penúltimo valor de temperatura:", temperaturas[-2])

Primer valor de temperatura: 10.1
Segundo valor de temperatura: 14.6
Último valor de temperatura: 20.3
Penúltimo valor de temperatura: 18.3


**Observations | Observaciones**

* In Python, the **0 index is the first element** of the list.
* Negative indices indicate that we start counting from the last item in the list.
* **Lists don't have a fixed length**, we can change them as we need.

---

* En Python, **el índice 0 indica el primer elemento** de la lista.
* Índices negativos indican que empezamos a contar desde el último elemento de la lista.
* **Las listas no tienen una longitud fija**, podemos cambiarla según lo necesitemos.

The indices also allow us to modify the values of the list. | Los índices además nos permiten modificar los valores de la lista.

In [ ]:
print("Temperature before: ", temperaturas)

In [24]:
temperaturas[0] = -2.3

print("Temperature after:", temperaturas)

Temperature before:  [10.1, 14.6, 18.3, 20.3]
Temperature after: [-2.3, 14.6, 18.3, 20.3]


We use `len` to find out how many values are in a list. | Usamos la función `len` para ver cuántos elementos tiene una lista.

In [26]:
len(temperaturas)

5

In case we want to extract a _slice of the list_ instead of a single element, it is possible.
If we want to obtain all the elements from the second to the fourth, without including the fourth one:

---

En caso de que queramos _extraer una porción_ de la lista en vez de un sólo elemento, es posible utilizar _slices_ o _porciones_.
Si queremos obtener todos los elementos desde el segundo hasta el cuarto, sin incluir:

In [27]:
temperaturas[1:4]

[14.6, 18.3, 20.3]

If we want to choose the first three elements: | Si queremos elegir los primeros tres elementos:

In [28]:
temperaturas[:3]

[-2.3, 14.6, 18.3]

Similarly, if we want to get all the elements after the third element. | De manera similar, si queremos obtener todos los elementos después del tercero.

In [29]:
temperaturas[3:]

[20.3, 23.5]

How can we use a _slice_ to access all elements except the last one? | ¿Cómo podemos usar un _slice_ para acceder a todos sus elementos menos el último?

In [30]:
temperaturas[:-1]

[-2.3, 14.6, 18.3, 20.3]

Can you create an empty list? | ¿Se puede crear una lista vacía?

In [43]:
lista_vacia = []

lista_vacia

[]

In [44]:
lista_vacia.append(1)

lista_vacia

[1]

#### Formative assessment 5

Let's define a list `my_list = [-3.0, -2.0, -1.0]`. What happens if we try to get the element with index 3 of the list, i.e. `my_list[3]`?

---

Definamos una lista `mi_lista = [-3.0, -2.0, -1.0]`. ¿Qué sucede si intentamos acceder al elemento con índice 3 de la lista, es decir `mi_lista[3]`?


1. We get `-1.0` | Obtenemos `-1.0`

2. We get an Error | Obtenemos un Error

3. We get `-3.0` | Obtenemos `-3.0`

In [1]:
# Solution | Solución

lista = [-3.0, -2.0, -1.0]

lista[3]

IndexError: list index out of range

#### Tuple | Tupla

_Tuples_ are like lists, but inmutable. 
If you have data that you want to store in a structure, but you know it will not be changed, tuples can be more efficient.

---

Las _tuplas_ son como una lista, pero inmutables.
Si tiene datos que desea almacenar en una estructura, pero sabe que no se cambiarán, las tuplas pueden ser más eficientes para su almacenamiento.

In [45]:
tupla = (2, 3.4, "March")

In [46]:
tupla[2]

'March'

#### Formative assessment 6

What will happen if we run the following lines of code? 

---

¿Qué pasá si ejecutamos las siguientes lineas de código?
```python
tupla = (2, 3.4, "March")
tupla.append("September")
print(tupla)
```

1. Return an error | Devuelve un error

2. Return the tuple with a new element | Devuelve la tupla con un nuevo elemento:
```
(2, 3.4, "March", "September")
```

3. Return the same tuple | Devuelve la misma tupla: 
```
(2, 3.4, "March")
```

In [47]:
# Solution | Solución

tupla.append("September")

AttributeError: 'tuple' object has no attribute 'append'

In [48]:
tupla + ("september")

TypeError: can only concatenate tuple (not "str") to tuple

If we want to add a new element in a tuple, we have to redefine the tuple: | Si queremos agregar un elemento nuevo a la tupla, tenemos que redefinir la tupla:

In [49]:
tupla = (2, 3.4, "March", "September")
tupla

(2, 3.4, 'March', 'September')

#### Dictionary | Diccionario

_Dictionaries_ are a way to efficiently store and retrieve data values by a _keyword_.
A dictionary is formed of key-value pairs, separated by commas, enclosed in curly brackets `{}`.
The key and the value are separated by a colon `:`, i.e. `key: value`.

---

Los diccionarios nos permiten almacenar cualquier tipo de datos identificándolos por una _palabra clave_.
Un diccionario está formado por pares de valores y claves, separados por comas, encerrados entre corchetes `{}`.
La clave y el valor están separados por dos puntos `:`, es decir, `clave: valor`.

In [36]:
my_dict = {'numerical' : 1, 'alphabetical': 'abc'}

print(my_dict)

{'numerical': 1, 'alphabetical': 'abc'}


We can access values using the keys between square brackets. | Podemos acceder a los valores usando las claves entre corchetes.

In [37]:
my_dict['numerical']

1

In [38]:
my_dict.get("alphabetical")

'abc'

In [39]:
my_dict.keys()

dict_keys(['numerical', 'alphabetical'])

Keys are inmutable (i.e. can't be changed) but values can be updated. | Las claves son inmutables (es decir, no se pueden cambiar) pero los valores se pueden actualizar.

In [40]:
my_dict['numerical'] = 5

We can also add new key-value pairs. | También podemos agregar nuevos pares clave-valor.

In [41]:
my_dict['binary'] = 1010001

print(my_dict)

{'numerical': 5, 'alphabetical': 'abc', 'binary': 1010001}


### Python Libraries | Librerías de Python

One of the advantages of using Python to process data is the ability to use libraries.
Libraries are **collections of modules** that contain functions to be used by other programs (for example, our notebooks and scripts). 
These functions usually save us a lot of time when performing certain tasks, since we do not need to write our own code to carry them out.

In addition, libraries are usually developed following best practices:
* Well designed code.
* They use version control.
* They have automated tests.
* Extensive documentation.
* Developed by a community.

We will use this opportunity to learn about **[NumPy](https://numpy.org/)**, which is one of the most used libraries in scientific computing. 

----

Una de las ventajas de usar Python para procesar datos es la posibilidad de usar librerías. 
Las librerías son **colecciones de módulos** que contienen funciones para ser usadas por otros programas (por ejemplo, nuestros notebooks y scripts).
Estas funciones suelen ahorrarnos mucho tiempo a la hora de realizar determinadas tareas, ya que no necesitamos escribir nuestro propio código para llevarlas a cabo.

Además, las librerías suelen están desarrolladas siguiendo las mejores prácticas:
* Código bien diseñado.
* Utilizan controladores de versiones.
* Poseen testeos automatizados.
* Documentación extensiva.
* Desarrolladas por una comunidad.

En esta oportunidad vamos a explorar la librería de **[NumPy](https://numpy.org/)**, una de las más utilizadas a la hora de realizar computación científica.

### Importing NumPy | Importando NumPy

In order to use a library, we first need to import it. | Para poder hacer uso de las librerías, primero necesitamos importarlas.

In [42]:
import numpy as np

This allows us to access the modules and functions of the library. | Esto nos permite acceder a los módulos y funciones de la librería. 

In [43]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

#### NumPy Arrays

NumPy introduces a new type of variable, the `numpy.array`.
Like lists, they allow you to store many values under a single variable:

---

NumPy introduce un nuevo tipo de variable, los `numpy.arrays` (o arreglos, en español).
Al igual que las listas, permiten guardar muchos valores bajo una única variable:

In [44]:
array_1d = np.array([2, 4, 6, 8.3, 4, 5])

print(array_1d)

type(array_1d)

[2.  4.  6.  8.3 4.  5. ]


numpy.ndarray

We can use indexes as we did with lists. | Podemos usar los índices como lo hacíamos con las listas.

In [45]:
array_1d[0]

2.0

In [46]:
array_1d[2:]

array([6. , 8.3, 4. , 5. ])

**What are the advantages and disadvantages of using `arrays`?** | **¿Cuáles son las ventajas y desventajas de usar `arrays`?**

* Arrays have a **fixed size**. Once created, we cannot add or remove values from it.
* Arrays **store a single type of variables** (floats or ints).
* They have a **more efficient** management of memory.
* All the **operations** we perform with _NumPy_ **are faster** than using _loops_ and _lists_.

----

* Los arrays **tienen tamaño fijo**. Una vez creados, no le podemos agregar o quitar valores.
* Los arrays **almacenan un único tipo de variables** (floats o ints).
* Tienen un **manejo mas eficiente** de la memoria.
* Todas **las operaciones** que realicemos con _NumPy_ **son más rápidas** que usar _loops_ y _listas_.

#### Array operations | Operaciones con arrays

Another advantage of using arrays is that many mathematical operations can be performed very easily.
For example, let's go back to the values of distance in inches.

----

Otra ventaja de usar arrays es que muchas operaciones matemáticas pueden realizarse muy fácilmente.
Por ejemplo, retomemos los valores de distancia medidas en pulgadas


In [47]:
inches = [10, 24.5, 90, 6.75, 90.7, 80]

# Convert the list into an array | Convertimos la lista en un array:
inches = np.array(inches)

print(inches)

[10.   24.5  90.    6.75 90.7  80.  ]


Convert to meters: | Convertimos a metros:

In [48]:
meters = inches * 25.4e-3 

print(meters)

[0.254   0.6223  2.286   0.17145 2.30378 2.032  ]


Add 10 meters: | Le sumo 10 metros:

In [49]:
meters + 10

array([10.254  , 10.6223 , 12.286  , 10.17145, 12.30378, 12.032  ])

It is also possible to operate with other arrays as long as they have the same shape. | También es posible operar con otros arreglos siempre y cuando tengan la misma forma.

In [50]:
precios = np.array([100, 200, 120, 98, 65, 3], dtype=float)

cantidades = np.array([2, 1, 3, 4, 9, 5])

print(precios, cantidades)

[100. 200. 120.  98.  65.   3.] [2 1 3 4 9 5]


In [51]:
costos = precios * cantidades

print(costos)

[200. 200. 360. 392. 585.  15.]


In [52]:
total = np.sum(costos)

print(total)

1752.0


##### Formative assessment 7 

Given 2 arrays `a` and `b` that have different number of elements.
What will happen if we add them?

---

Dados 2 arrays `a` y `b` que tiene diferente número de elementos. 
¿Qué pasará si los sumamos?:
```python
a = np.array([1, 2, 3])
b = np.array([4, 5])

a + b
```


1.  Add element by element and we get the following array | Suma elemento a elemento y obtenemos el siguiente array:
```
[5, 7, 3]
```

2. Concatenate the 2 arrays | Concatena los 2 arrays:
```
[1, 2, 3, 4, 5]
```

3. Return an error | obtenemos un error

In [53]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

a + b

# They have to have the same shape | Deben tener la misma forma

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#### Multidimensional arrays | Arrays multidimensional

It is possible to define multidimensional arrays. 
For example, a 2D array would look like a matrix:

----

Es posible definir arreglos multidimensional.
Por ejemplo, un arreglo 2D se vería como una matriz:

In [54]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2d)

[[1 2 3]
 [4 5 6]]


In [55]:
array_2d.shape

(2, 3)

In [56]:
type(array_2d.shape)

tuple

We can access each element of a 2D array through its indices. | Podemos acceder a cada elemento de un arreglo 2D a través de sus índices:

In [57]:
array_2d[0, 1]

2

We can extract a portion of the array. | Podemos extraer una porción del array:

In [58]:
array_2d[:, 1]

array([2, 5])

#### Some NumPy functions | Algunas funciones de NumPy

Every time we make use of the functions of a library, it is advisable to read its documentation

---

Cada vez que hagamos uso de las funciones de una librería, es recomendable leer su documentación.

In [59]:
np.mean?

Signature:
np.mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>,
)
Docstring:
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating poi

In [60]:
print(array_1d)

print(
    "Mean:", np.mean(array_1d),
    "Standard deviation:", np.std(array_1d),
    "Max:", np.max(array_1d),
    "Min:", np.min(array_1d),
    "Square root:", np.sqrt(array_1d)
     )

[2.  4.  6.  8.3 4.  5. ]
Mean: 4.883333333333334 Standard deviation: 1.9497150788997066 Max: 8.3 Min: 2.0 Square root: [1.41421356 2.         2.44948974 2.88097206 2.         2.23606798]


### Homework | Tarea

Before doing your homework, _check_ that you have a _local repository_ called `coco_coding_homework`.
If you don't have it, create this repository according to what you learned in the _Git session_.
In this repository you will push all the notebooks with the solution of the proposed activities.

Then, _create a notebook_ called `homework_python_basics.ipynb` into the _local repository_.
There you will solve the activities proposed below.
After _commit_ your notebook's changes, _push_ them into the _remote repository_ in your GitHub account.
In this way, one of the trainers will be able to see your answers and give you feedback.

---

Antes de hacer la tarea, _verifique_ que tiene creado un repositorio local nombre `coco_coding_homework`. 
Si no lo tiene, cree el repositorio según lo aprendido en la _sesión de Git_.
En este repositorio subirá todos los notebooks con la solución de las actividades propuestas.

Luego _cree un notebook_ llamado `homework_python_basics.ipynb` en el _repositorio local_.
Alli es donde resolverá las actividades propuestas a continuación.
Luego de hacer un _commit_ a los cambios que hizo en el notebook, haga un _push_ para subir los cambias al _repositorio remoto_ en sucuenta de GitHub. 
De esta forma, alguno de los trainers podrá ver sus respuestas y darle una devolución de las actividades resueltas. 

#### 1° Task

1. Create a list with the names of every planet in the solar system (in order)
2. Have Python tell you how many planets there are by examining your list
3. Print the first four planets in the solar system (the rocky planets)
4. Print the planet if it has an s at the end in its name

---

1. Crea una lista con los nombres de todos los planetas del sistema solar (en orden)
2. Haz que Python te diga cuántos planetas hay examinando tu lista
3. Muestre los primeros cuatro planetas  del sistema solar (los planetas rocosos)
4. Imprimir el nombre del planeta que tiene una s al final de su nombre

#### 2° Task

A colleague from the United States shared with us the following temperature measurement, given in Fahrenheit:

$$
T = 30.3^\circ \text{F}
$$

Convert this value to degrees Celsius, knowing that:
$$[^\circ \text{C}] = \frac{5}{9} ([^\circ \text{F}] - 32) $$ 

Requirements:

* Assign the received data to a variable.
* Apply the unit transformation using this variable.
* Save the data in Celsius in another variable.
* Use the print function to display both results.

---

Un colega de Estados Unidos nos ha compartido la siguiente medición de temperatura de suelo dada en Fahrenheit:
$$ T = 30.3 ^\circ\text{F} $$

Conviertan este valor a grados Celsius, sabiendo que:
$$ [^\circ\text{C}] = \frac{5}{9} ([^\circ\text{F}] - 32) $$

Requerimientos:

* Asignar el dato recibido a una variable.
* Aplicar la transformación de unidades usando esta variable.
* Guardar el dato en Celsius en otra variable.
* Utilizar la función print para mostrar ambos resultados.



#### 3° Task

Given the array: `([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])`, investigate the `numpy` library documentation for reshape the array to be 4x4.

----

Dado el array: `([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])` investigue la documentación de la librería `numpy` para "reshape" o reformular el array para que sea de 4x4.


#### 4° Task

`NumPy` allows us to apply mathematical functions.

Calculate the sine and cosine of the angles 0, 30, 45, 60 and 90 given in degrees:
1. Create an array with the angles in degrees.
2. Convert the angles to radians.
3. Calculate the sine and cosine of these angles and store them in two different arrays.

_Investigate the `numpy` library to find the functions to convert the angles from degrees to radians and calculate the sine and cosine._

---

`NumPy` nos permite también aplicar funciones matemáticas. 

Calcule el seno y el coseno de los ángulos: 0, 30, 45, 60 y 90 dados en grados:
1. Cree un array con los ángulos mencionados en grados.
2. Convierta los ángulos a radianes.
3. Calcule el seno y el coseno de estos ángulos y guárdelos en dos arrays diferentes.

_Investigue la librería `numpy` para encontrar las funciones que permitan convertir los ángulos en grados a radianes y calcular el seno y coseno._

#### 5° Task


**Finite differences | Diferencias finitas**

A common approximation for computing derivatives of functions is a finite difference approximation:

$$\frac{d}{dx} y(x) = \frac{y(x + \Delta x) - y(x)}{\Delta x}$$

or for discrete data

$$\frac{d}{dx} y(x_i) = \frac{y(x_i + \Delta x) - y(x_i)}{\Delta x} = \frac{y(x_{i+1}) - y(x_i)}{x_{i+1} - x_{i}}$$

This operation can be accomplished using index, slice and vectorized algebraic operations.
Try to solve it for the quadratic function!

Now, read the numpy documentation to find a function to calculate $\frac{d}{dx} y(x_i)$.

----

Una aproximación común para calcular derivadas de funciones es una aproximación en diferencias finitas:

$$\frac{d}{dx} y(x) = \frac{y(x + \Delta x) - y(x)}{\Delta x}$$

o para datos discretos

$$\frac{d}{dx} y(x_i) = \frac{y(x_i + \Delta x) - y(x_i)}{\Delta x} = \frac{y(x_{i+1}) - y(x_i)}{x_{i+1} - x_{i}}$$

Esta operación se puede realizar utilizando las operaciones algebraicas vectorizadas, indices y silce. 
¡Intenta calcularlo para la función cuadrática!

Ahora, lea la documentación de Numpy para encontrar una función para poder calcular $\frac{d}{dx} y(x_i)$. 

## Extra material to keep learning | Material extra para seguir aprendiendo

* [How use JupyterLab by Software Carpentry](https://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html)

* [Apuntes generates de Python](https://drive.google.com/file/d/12_1yUhaGeoH7wLGqrHiSx987FMdqM_Mv/view)

* [Introduction to Python1](https://johnfoster.pge.utexas.edu/numerical-methods-book/PythonIntro.html)

* [Plotting and Programming in Python by Software Carpenty](https://swcarpentry.github.io/python-novice-gapminder/index.html)

* [NumPy tutorials](https://numpy.org/learn/)