# Welcome to learning Python!

These notebooks contain a mix of text and code. 
This makes it easy to experiment with code and keep documentation like this in the same place. 
You can execute each cell individually, and therefore work incrementally with your code. 
If you want to execute a cell, you can press the `►` button above when you have highlighted the cell. 
Alternatively, you can hit `Shift + Enter` to execute and progress to next cell or alternatively `Ctrl + Enter` (Windows) or `Cmd + Enter` (Mac). 
_Take your time to experiment with it if you like and don't hesitate to ask or search for things in your favorite browser._


**In this notebook we will learn about**:
* Variables
* Types of data
* Different data structures
* Working with Numpy arrays

----

Estos notebooks contienen una combinación de texto y código, lo que facilita la experimentación con el código y mantiene una documentación como esta en el mismo lugar. 
En los notebooks se puede ejecutar cada celda individualmente y, por lo tanto, trabajar de forma incremental con tu código. 
Si deseas ejecutar una celda, puedes presionar el botón `►` de arriba cuando se haya resaltado la celda o presionar `Shift + Enter` para ejecutar y avanzar a la siguiente celda. Puedes usar alternativamente `Ctrl + Enter` (Windows) o `Cmd + Enter` (Mac).
_Tómate tu tiempo para experimentar con él si quieres y no dudes en preguntar o buscar cosas en tu navegador favorito._

**En este notebook aprenderemos sobre**: 
* Variables
* Tipo de datos
* Diferentes estructuras de datos
* Trabajar con Numpy arrays


## Variables and data type / Variables y tipos de datos 

A _variable_ allows us to store a value.
In Python, we can assign a value to a variable, using the equals sign `=`.

----

Una _variable_ nos permite almacenar un valor en un lugar determinado. 
En Python usamos el simbolo `=` para asignar un valor a una variable.

In [1]:
alumni = 15
course_name = "CoCo"

The keyword `print()` is a function in Python.
We can use it to see the value store in the variable.

----

`print()` es una funcion en Python, que usamos para examinar el valor asignado a una variable.

In [2]:
print(alumni)

15


In [3]:
print(course_name, "course has", alumni, "alumni")

CoCo course has 15 alumni


Moreover, variables can easily be updated.
Try it out below!

---

Además, las variables se pueden actualizar fácilmente.
¡Probémoslo!

**Data Types / Tipos de datos**

There are several different data types that we will be exploring in the course, including:
* integer
* string
* float

---

Hay diferentes tipos de datos que vamos a ver en el curso, los cuales son:
* integers (int): números enteros
* strings (str): cadena de caracteres
* floats (float): valores de punto flotante (representación aproximada de números reales).


In [4]:
type(alumni)

int

In [5]:
type(course_name)

str

In [6]:
half_alumni = alumni / 2

print(half_alumni, "is", type(half_alumni))

7.5 is <class 'float'>


If you want to concatenate two or more strings, there are several ways to achieve this in Python. 
The simplest method is to use `+`

---

Si desea concatenar dos o más cadenas de caracteres juntas hay varias formas de hacerlo.
La más común es usar `+`.

In [7]:
saludo = "hola" + " " + "mundo"

print(saludo)

hola mundo


### Formative assessment 1

What would be the difference between an integer and float data type?
How would we convert a float into an integer?
(Give a best guess answer)

---

¿Cuál sería la diferencia entre un tipo de datos entero y flotante?
¿Cómo convertiríamos un flotante en un número entero?
(Dar una mejor respuesta posible)

In [8]:
# Solutiopn / solucion

Int_alumni = int(half_alumni)

print(half_alumni, "is", type(half_alumni), 
      "but", Int_alumni, "is", type(Int_alumni)
     )

7.5 is <class 'float'> but 7 is <class 'int'>


### Formative assessment 2

What will be the output of the next cell? / ¿Cual será el output de la siguiente celda?

```
channel = 100.0
type(channel)
```

1. int

2. float

3. str

In [9]:
# Solution / solucion

channel = 100.0
type(channel)

float

### Mathematical operations / Operaciones matemáticas

All of the standard calculator arithmetic operations are available between variables.

We measure a certain geophysical variable at a height of 53.2 meters above sea level: 

---

Podemos aplicar diferentes operaciones aritméticas entre distintas variables.

Medimos una determinada variable geofísica a una altura de 53.2 metros sobre el nivel del mar:

In [10]:
sea_height = 53.2

In [11]:
sea_height

53.2

**Addition / Suma**

In [12]:
sea_height + 10.6

63.800000000000004

In [13]:
sea_height - 3.5

49.7

**Multiplication / Multiplicación**

In [14]:
sea_height * 2

106.4

**Division / División**

In [15]:
sea_height / 2

26.6

In [16]:
sea_height // 2

26.0

**Power / Potencia**

In [17]:
sea_height ** 2

2830.2400000000002

## Data Structures

A data structure is a term to describe a type of "data container". 
They are used to store multiples of variables and provide certain accessor functions to extract them from the container. 

---

Una estructura de datos es un término para describir un tipo de "contenedor de datos".
Se utilizan para almacenar múltiples variables y proporciona ciertas funciones de acceso para extraerlas del contenedor. 

### List / Listas

Python lists are used to store a collection of data.
A list is composed of comma-separated values between square brackets.

---

Las listas nos permiten guardar múltiples valores bajo una misma variable.
Una lista es una lista de valores separados por comas entre corchetes.


In [18]:
impares = [1, 3, 5, 7, 9]

type(impares)

list

It can store heterogeneous data or you can even have lists of lists

---

Las listas pueden contener datos heterogéneos (diferentes tipos de variables), hasta listas.

In [19]:
list_heterogeneous = ["agua", 20.1, 52]

anidadas = [[1, 2, 3], 3.0, "hielo"]

print(list_heterogeneous, anidadas)

['agua', 20.1, 52] [[1, 2, 3], 3.0, 'hielo']


To access the first element of the list, which is a list

---

Accededemos al primer elemento de la lista, que es una lista.

In [20]:
anidadas[0]

[1, 2, 3]

We can access to the values housed in a list through its indices

---

Podemos acceder a los valores alojados dentro de una lista a través de sus índices.

In [21]:
temperaturas = [10.1, 14.6, 18.3, 20.3]

In [22]:
temperaturas

[10.1, 14.6, 18.3, 20.3]

In [23]:
print("Primer valor de temperatura:", temperaturas[0])
print("Segundo valor de temperatura:", temperaturas[1])
print("Último valor de temperatura:", temperaturas[-1])
print("Penúltimo valor de temperatura:", temperaturas[-2])

Primer valor de temperatura: 10.1
Segundo valor de temperatura: 14.6
Último valor de temperatura: 20.3
Penúltimo valor de temperatura: 18.3


**Observations:**

* In Python, the 0 index is the first element.
* Negative indices indicate that we start counting from the last item in the list.
* Lists have a method called `append` that allows us to add values.
* The lists do not have a fixed length, we can change it as we need.

---

**Observaciones**

* En Python, el índice 0 indica el primer elemento.
* Índices negativos indican que empezamos a contar desde el último elemento de la lista.
* Las listas poseen un método llamado `append` que nos permite agregar valores.
* Las listas no tienen una longitud fija, podemos cambiarla según lo necesitemos.

The indices also allow us to modify the values of the list

---

Los índices además nos permiten modificar los valores de la lista.

In [24]:
print("Temperature before: ", temperaturas)
temperaturas[0] = -2.3

print("Temperature after:", temperaturas)

Temperature before:  [10.1, 14.6, 18.3, 20.3]
Temperature after: [-2.3, 14.6, 18.3, 20.3]


In [25]:
temperaturas.append(23.5)

print(temperaturas)

[-2.3, 14.6, 18.3, 20.3, 23.5]


We use `len` to find out how many values are in a list.

---

Usamos la función `len` para ver cuántos elementos tiene una lista.

In [26]:
len(temperaturas)

5

In case we want to extract a _slice of the list_ instead of a single element, it is possible.
If we want to obtain all the elements from the second to the fourth, without including the fourth one:

---

En caso de que querramos _extraer una porción_ de la lista en vez de un sólo elemento, es posible utilizar _slices_ o _porciones_.
Si queremos obtener todos los elementos desde el segundo hasta el cuarto, sin incluir:

In [27]:
temperaturas[1:4]

[14.6, 18.3, 20.3]

If we want to choose the first three elements

---

Si queremos elegir los primeros tres elementos:

In [28]:
temperaturas[:3]

[-2.3, 14.6, 18.3]

Similarly, if we want to get all the elements after the third element

---

De manera similar, si queremos obtener todos los elementos después del tercero:

In [29]:
temperaturas[3:]

[20.3, 23.5]

How can we use a slice to access all its elements except the last one?

---

¿Cómo podemos usar un _slice_ para acceder a todos sus elementos menos el último?

In [30]:
temperaturas[:-1]

[-2.3, 14.6, 18.3, 20.3]

We can concatenate lists using `+`

---

Podemos concatenar listas usando `+`.

In [31]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

**Can you create an empty list?**

---

**¿Se puede crear una lista vacía?**

In [32]:
lista_vacia = []

lista_vacia

[]

### Formative assessment 3

Lets define a list `my_list = [-3.0, -2.0, -1.0]`. What happens if I try to get the element with index 3 of the list, i.e. `my_list[3]`?

1. We get an Error

2. We get `-1.0`

3. We get `-3.0`

---

Definamos una lista `mi_lista = [-3.0, -2.0, -1.0]`. ¿Qué sucede si intentamos acceder al elemento con índice 3 de la lista, es decir `mi_lista[3]`?

1. Obtenemos un Error

2. Obtenemos `-1.0`

3. Obtenemos `-3.0`

In [4]:
# Solution / Solución

lista = [-3.0, -2.0, -1.0]

lista[10]

IndexError: list index out of range

### Tuple / Tupla

Tuples are like a list, but immutables. 
If you have data that you want to store in a structure, but you know it will not be changed, tuples can be more efficient.

---

Las tuplas son como una lista, pero inmutables.
Si tiene datos que desea almacenar en una estructura, pero sabe que no se cambiarán, las tuplas pueden ser más eficientes para su almacenamiento.

In [5]:
tuple = (2, 3.4, "March")

In [6]:
tuple[2]

'March'

### Dictionary / Diccionario

Dictionaries are a way to efficiently store and retrieve data values by a _keyword_.
A dictionary is formed of value-key pairs, separated by commas, enclosed in curly brackets `{}`.
The key and the value are separated by a colon `:`, i.e. `key: value`.

---

Los diccionarios nos permiten almacenar cualquier tipo de datos identificandolos por una _palabra clave_.
Un diccionario está formado por pares de valores y claves, separados por comas, encerrados entre corchetes `{}`.
La clave y el valor están separados por dos puntos `:`, es decir, `clave: valor`.

In [36]:
my_dict = {'numerical' : 1, 'alphabetical': 'abc'}

print(my_dict)

{'numerical': 1, 'alphabetical': 'abc'}


We can access values using the keys between square brackets. / Podemos acceder a los valores usando las claves entre corchetes.

In [37]:
my_dict['numerical']

1

In [38]:
my_dict.get("alphabetical")

'abc'

In [39]:
my_dict.keys()

dict_keys(['numerical', 'alphabetical'])

Keys are immutables (i.e. can't be changed) but values can be updated.

---

Las claves son inmutables (es decir, no se pueden cambiar) pero los valores se pueden actualizar.

In [40]:
my_dict['numerical'] = 5

We can also add new key-value pairs / También podemos agregar nuevos pares clave-valor.

In [41]:
my_dict['binary'] = 1010001

print (my_dict)

{'numerical': 5, 'alphabetical': 'abc', 'binary': 1010001}


## Python Libraries / Librerias de Python

One of the advantages of using Python to process data is the ability to use libraries.
Libraries are **collections of modules** that contain functions to be used by other programs (for example, our notebooks and scripts). 
These functions usually save us a lot of time when performing certain tasks, since we do not need to write our own code to carry them out.

In addition, libraries are usually developed following best practices:
* Well designed code.
* They use version drivers.
* They have automated tests.
* Extensive documentation.
* Developed by a community.

In this opportunity, we will learn about **[Numpy](https://numpy.org/)**, which is one of the most used libraries when it comes to scientific computing. 

----

Una de las ventajas de usar Python para procesar datos es la posibilidad de usar librerías. 
Las librerías son **colecciones de módulos** que contienen funciones para ser usadas por otros programas (por ejemplo, nuestros notebooks y scripts).
Estas funciones suelen ahorrarnos mucho tiempo a la hora de realizar determinadas tareas, ya que no necesitamos escribir nuestro propio código para llevarlas a cabo.

Además, las librerías suelen están desarrolladas siguiendo las mejores prácticas:
* Código bien diseñado.
* Utilizan controladores de versiones.
* Poseen testeos automatizados.
* Documentación extensiva.
* Desarrolladas por una comunidad.

En esta oportunidad vamos a explorar la libreria de **[Numpy](https://numpy.org/)**, una de las más utilizadas a la hora de realizar computación científica.

### Importing Numpy | Importando Numpy

In order to make use of the libraries, we first need to import them

---

Para poder hacer uso de las librerías, primero necesitamos importarlas.

In [6]:
import numpy as np

This allows us to access the modules and functions of the library

---

Esto nos permite acceder a los módulos y funciones de la librería. 

In [44]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

### Numpy Arrays

NumPy introduces a new type of variable, the `numpy.array`.
Like lists, they allow you to store many values under a single variable:

---

NumPy introduce un nuevo tipo de variable, los `numpy.arrays` (o arreglos, en español).
Al igual que las listas, permiten guardar muchos valores bajo una única variable:

In [45]:
array_1d = np.array([2, 4, 6, 8.3, 4, 5])

print(array_1d)

type(array_1d)

[2.  4.  6.  8.3 4.  5. ]


numpy.ndarray

We can use indexes as we did with lists

---

Podemos usar los índices como lo hacíamos con las listas:

In [46]:
array_1d[0]

2.0

In [47]:
array_1d[2:]

array([6. , 8.3, 4. , 5. ])

**What are the advantages and disadvantages of using `arrays`?**

* Arrays have a fixed size. Once created, we cannot add or remove values from it.
* Arrays store a single type of variables (floats or ints).
* They have a more efficient management of memory.
* All the operations we perform with _NumPy_ are faster than using _forloops_ and _lists_.

----

**¿Cuáles son las ventajas y desventajas de usar `arrays`?**

* Los arrays tienen tamaño fijo. Una vez creados, no le podemos agregar o quitar valores.
* Los arrays almacenan un único tipo de variables (floats o ints).
* Tienen un manejo mas eficiente de la memoria.
* Todas las operaciones que realicemos con _NumPy_ son más rápidas que usar _forloops_ y _listas_.


### Array operations / Operaciones con arrays

Another advantage of using arrays is that many mathematical operations can be performed very easily.
For example, let's go back to the values of distance in inches.

----

Otra ventaja de usar arrays es que muchas operaciones matemáticas pueden realizarse muy fácilmente.
Por ejemplo, retomemos los valores de distancia medidas en pulgadas


In [48]:
inches = [10, 24.5, 90, 6.75, 90.7, 80]

# Convert the list into an array / Convertimos la lista en un array:
inches = np.array(inches)

print(inches)

[10.   24.5  90.    6.75 90.7  80.  ]


Convert to meters

---

Convertimos a metros:

In [49]:
meters = inches * 25.4e-3 

print(meters)

[0.254   0.6223  2.286   0.17145 2.30378 2.032  ]


Add 10 meters 

---

Le sumo 10 metros:

In [50]:
meters + 10

array([10.254  , 10.6223 , 12.286  , 10.17145, 12.30378, 12.032  ])

It is also possible to operate with other arrays as long as they have the same shape.

---

También es posible operar con otros arreglos siempre y cuando tengan la misma forma.

In [51]:
precios = np.array([100, 200, 120, 98, 65, 3], dtype=float)
cantidades = np.array([2, 1, 3, 4, 9, 5])

print(precios, cantidades)

[100. 200. 120.  98.  65.   3.] [2 1 3 4 9 5]


In [52]:
costos = precios * cantidades

print(costos)

[200. 200. 360. 392. 585.  15.]


In [53]:
total = np.sum(costos)

print(total)

1752.0


In [54]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Multidimensional arrays / Arrays multidimensionales

It is possible to define multidimensional arrays.
For example, a 2D array would look like an matrix:

----

Es posible definir arreglos multidimensionales.
Por ejemplo, un arreglo 2D se vería como una matriz:

In [55]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2d)


[[1 2 3]
 [4 5 6]]


In [56]:
array_2d.shape

(2, 3)

In [57]:
type(array_2d.shape)

tuple

We can access each element of a 2D array through its indexes

---

Podemos acceder a cada elemento de un arreglo 2D a través de sus índices:

In [58]:
array_2d[0, 1]

2

We can extract a portion of the array

---

Podemos extraer una porción del array:

In [59]:
array_2d[:, 1]

array([2, 5])

### Some Numpy functions / Algunas funciones de Numpy

Every time we make use of the functions of a library, it is advisable to read its documentation

---

Cada vez que hagamos uso de las funciones de una librería, es recomendable leer su documentación.

In [7]:
np.mean?

In [60]:
print(array_1d)

print(
    "Mean:", np.mean(array_1d),
    "Standard deviation:", np.std(array_1d),
    "Max:", np.max(array_1d),
    "Min:", np.min(array_1d),
    "Square root:", np.sqrt(array_1d)
     )

[2.  4.  6.  8.3 4.  5. ]
Mean: 4.883333333333334 Standard deviation: 1.9497150788997066 Max: 8.3 Min: 2.0 Square root: [1.41421356 2.         2.44948974 2.88097206 2.         2.23606798]


## Homework / Tarea

### 1° Task

A colleague from the United States shared with us the following temperature measurement, given in Fahrenheit:

$$
T = 30.3^\circ \text{F}
$$

Convert this value to degrees Celsius, knowing that:
$$[^\circ \text{C}] = \frac{5}{9} ([^\circ \text{F}] - 32) $$ 

Requirements:

* Assign the received data to a variable.
* Apply the unit transformation using this variable.
* Save the data in Celsius in another variable.
* Use the print function to display both results.

---

Un colega de Estados Unidos nos ha compartido la siguiente medición de temperatura de suelo dada en Fahrenheit:
$$ T = 30.3 ^\circ\text{F} $$

Conviertan este valor a grados Celsius, sabiendo que:
$$ [^\circ\text{C}] = \frac{5}{9} ([^\circ\text{F}] - 32) $$

Requerimientos:

* Asignar el dato recibido a una variable.
* Aplicar la transformación de unidades usando esta variable.
* Guardar el dato en Celsius en otra variable.
* Utilizar la función print para mostrar ambos resultados.



### 2° Task

Now, convert the following list of temperatures in Fahrenheit to Celsius.

temperatures_F = [30.3, 20.1, 46.5, 34.1, 42.3]

---

Ahora, convierta la siguiente lista de temperaturas en Fahrenheit a grados Centígrados unado un for loop.

temperaturas_F = [30.3, 20.1, 46.5, 34.1, 42.3]

### 3° Task

Given the array: `([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])`, investigate the `numpy` library documentation for reshape the array to be 4x4.

----

Dado el array: `([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])` investigue la documentacion de la libreria `numpy` para "reshape" o reformular el array para que sea de 4x4.


### 4° Task

`Numpy` allows us to apply mathematical functions.

Calculate the sine and cosine of the angles 0, 30, 45, 60 and 90 given in degrees:
1. Create an array with the angles in degrees.
2. Convert the angles to radians.
3. Calculate the sine and cosine of these angles and store them in two different arrays.

_Investigate the `numpy` library to find the functions to convert the angles from degrees to radians and calculate the sine and cosine._

---

`Numpy` nos permite también aplicar funciones matemáticas. 

Calcule el seno y el coseno de los angulos: 0, 30, 45, 60 y 90 dados en grados:
1. Cree un array con los ángulos mencionados en grados.
2. Convierta los ángulos a radianes.
3. Calcule el seno y el coseno de estos ángulos y guárdelos en dos arrays diferentes.

_Investigue la libreria `numpy` para encontrar las funciones que permitan convertir los ángulos en grados a radianes y calcular el seno y coseno._

### 5° Task


**Finite differences**

A common approximation for computing derivatives of functions is a finite difference approximation:

$$\frac{d}{dx} y(x) = \frac{y(x + \Delta x) - y(x)}{\Delta x}$$

or for discrete data

$$\frac{d}{dx} y(x_i) = \frac{y(x_i + \Delta x) - y(x_i)}{\Delta x} = \frac{y(x_{i+1}) - y(x_i)}{x_{i+1} - x_{i}}$$

This operation can be accomplished using index, silce and vectorized algebraic operations.
Try to solve it!

Now, read the numpy documantation to find a function to calculate $\frac{d}{dx} y(x_i)$.

----

**Diferencias finitas**

Una aproximación común para calcular derivadas de funciones es una aproximación en diferencias finitas:

$$\frac{d}{dx} y(x) = \frac{y(x + \Delta x) - y(x)}{\Delta x}$$

o para datos discretos

$$\frac{d}{dx} y(x_i) = \frac{y(x_i + \Delta x) - y(x_i)}{\Delta x} = \frac{y(x_{i+1}) - y(x_i)}{x_{i+1} - x_{i}}$$

Esta operación se puede realizar utilizando las operaciones algebraicas vectorizadas, indices y silce. 
¡Intenta calcularlo!

Ahora, lea la documentación de Numpy para encontrar una función para poder calcular $\frac{d}{dx} y(x_i)$. 

## Extra material to keep learning / Material extra para seguir aprendiendo

* [How use JupyterLab by Software Carpentry](https://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html)

* [Apuntes generates de Python](https://drive.google.com/file/d/12_1yUhaGeoH7wLGqrHiSx987FMdqM_Mv/view)

* [Introduction to Python1](https://johnfoster.pge.utexas.edu/numerical-methods-book/PythonIntro.html)

* [Plotting and Programming in Python by Software Carpenty](https://swcarpentry.github.io/python-novice-gapminder/index.html)

* [NumPy tutorials](https://numpy.org/learn/)