# Python Libraries / Librerias de Python

One of the advantages of using Python to process data is the ability to use libraries.
Libraries are **collections of modules** that contain functions to be used by other programs (for example, our notebooks and scripts). 
These functions usually save us a lot of time when performing certain tasks, since we do not need to write our own code to carry them out.

In addition, libraries are usually developed following best practices:
* Well designed code.
* They use version drivers.
* They have automated tests.
* Extensive documentation.
* Developed by a community.

----

Una de las ventajas de usar Python para procesar datos es la posibilidad de usar librerías. 
Las librerías son **colecciones de módulos** que contienen funciones para ser usadas por otros programas (por ejemplo, nuestros notebooks y scripts).
Estas funciones suelen ahorrarnos mucho tiempo a la hora de realizar determinadas tareas, ya que no necesitamos escribir nuestro propio código para llevarlas a cabo.

Además, las librerías suelen están desarrolladas siguiendo las mejores prácticas:
* Código bien diseñado.
* Utilizan controladores de versiones.
* Poseen testeos automatizados.
* Documentación extensiva.
* Desarrolladas por una comunidad.

## Numpy

[Numpy](https://numpy.org/) is one of the most used libraries when it comes to scientific computing. 

----

[Numpy](https://numpy.org/) es una de las librerías más utilizadas a la hora de realizar computación científica.

### Importing Numpy

In order to make use of the libraries, we first need to import them.

----

Para poder hacer uso de las librerías, primero necesitamos importarlas.

In [1]:
import numpy

This allows us to access the modules and functions of the library. 
For example, Numpy offers us a function to calculate the mean of a series of values:

---

Esto nos permite acceder a los módulos y funciones de la librería. 
Por ejemplo, Numpy nos ofrece una función para calcular la media de una serie de valores:

In [2]:
numpy.mean([1, 2, 3, 4])

2.5

Many times it is tedious to write the entire library name every time we want to use its functions or modules. 
One option is to import them under an alias. 
For example, NumPy is usually imported under the name `np`.

----

Muchas veces resulta tedioso escribir todo el nombre de la librería cada vez que queremos usar sus funciones o módulos. 
Una opción es importarlas bajo un alias. 
Por ejemplo, NumPy se suele importar bajo el nombre `np`.

In [3]:
import numpy as np

np.mean([1, 2, 3, 4])

2.5

### Numpy Arrays

NumPy introduces a new type of variable, the `numpy.array`.

Like lists, they allow you to store many values under a single variable:

---

NumPy introduce un nuevo tipo de variable, los `numpy.arrays` (o arreglos, en español).

Al igual que las listas, permiten guardar muchos valores bajo una única variable:

In [16]:
array_1d = np.array([2, 4, 6, 8.3, 4, 5])

print(array_1d)

type(array_1d)

[2.  4.  6.  8.3 4.  5. ]


numpy.ndarray

We can use indexes as we did with lists / Podemos usar los índices como lo hacíamos con las listas:

In [17]:
array_1d[0]

2.0

In [18]:
array_1d[2:]

array([6. , 8.3, 4. , 5. ])

**What are the advantages and disadvantages of using `arrays`?**

* Arrays have a fixed size. Once created, we cannot add or remove values from it.
* Arrays store a single type of variables (floats or ints).
* They have a more efficient management of memory.
* All the operations we perform with _NumPy_ are faster than using _forloops_ and _lists_.

----

**¿Cuáles son las ventajas y desventajas de usar `arrays`?**

* Los arrays tienen tamaño fijo. Una vez creados, no le podemos agregar o quitar valores.
* Los arrays almacenan un único tipo de variables (floats o ints).
* Tienen un manejo mas eficiente de la memoria.
* Todas las operaciones que realicemos con _NumPy_ son más rápidas que usar _forloops_ y _lists_.


### Array operations / Operaciones con arrays

Another advantage of using arrays is that many mathematical operations can be performed very easily.

For example, let's go back to the temperature values received in Fahrenheit.

----

Otra ventaja de usar arrays es que muchas operaciones matemáticas pueden realizarse muy facilmente.

Por ejemplo, retomemos los valores de temperatura recibidos en Farenheit.


In [8]:
temperaturas_F = [30.3, 20.1, 46.5, 34.1, 42.3]

# Convert the list into an array / Convertimos la lista en un array:
temperaturas_F = np.array(temperaturas_F)

print(temperaturas_F)

[30.3 20.1 46.5 34.1 42.3]


Convert to Celsius / Convertimos a grados Celsius:

In [9]:
temperaturas_C = (temperaturas_F - 32) * 5 / 9

print(temperaturas_C)

[-0.94444444 -6.61111111  8.05555556  1.16666667  5.72222222]


It is also possible to operate with other matrices as long as they have the same shape.

---

También es posible operar con otras matrices siempre y cuando tengan la misma forma.

In [10]:
precios = np.array([100, 200, 120, 98, 65, 3], dtype=float)
cantidades = np.array([2, 1, 3, 4, 9, 5])

print(precios, cantidades)

[100. 200. 120.  98.  65.   3.] [2 1 3 4 9 5]


In [11]:
costos = precios * cantidades

print(costos)

[200. 200. 360. 392. 585.  15.]


In [12]:
total = np.sum(costos)

print(total)

1752.0


In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### Multidimensional arrays / Arrays multidimensionales

It is possible to define multidimensional arrays.
For example, a 2D array would look like an array:

----

Es posible definir arreglos multidimensionales.
Por ejemplo, un arreglo 2D se vería como una matriz:

In [19]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(array_2d)


[[1 2 3]
 [4 5 6]]


In [20]:
array_2d.shape

(2, 3)

In [21]:
type(array_2d.shape)

tuple

We can access each element of a 2D array through its indexes / Podemos acceder a cada elemento de un arreglo 2D a través de sus índices:

In [22]:
array_2d[0, 1]

2

We can extract a portion of the array / Podemos extraer una porción del array:

In [23]:
array_2d[:, 1]

array([2, 5])

### Some Numpy functions / Algunas funciones de Numpy

Every time we make use of the functions of a library, it is advisable to read its documentation.

---

Cada vez que hagamos uso de las funciones de una librería, es recomendable leer su documentación.

In [27]:
print(array_1d)

print(
    "Mean:", np.mean(array_1d),
    "Standard deviation:", np.std(array_1d),
    "Max:", np.max(array_1d),
    "Min:", np.min(array_1d),
    "Square root:", np.sqrt(array_1d)
     )

[2.  4.  6.  8.3 4.  5. ]
Mean: 4.883333333333334 Standard deviation: 1.9497150788997066 Max: 8.3 Min: 2.0 Square root: [1.41421356 2.         2.44948974 2.88097206 2.         2.23606798]


### Homework 

**1° Task**

Given the array: `([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])`, investigate the `numpy` library for reshape the array to be 4x4.

----

Dado el array: `([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])` investigue la libreria `numpy` para para reshape el array para que sea de 4x4.


In [28]:
# Solution 
datos = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
np.reshape(datos, (4, 4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**2° Task**

`Numpy` allows us to apply mathematical functions.

Calculate the sine and cosine of the angles 0, 30, 45, 60 and 90 given in degrees:
1. Create an array with the angles in degrees.
2. Convert the angles to radians.
3. Calculate the sine and cosine of these angles and store them in two different arrays.

_Investigate the `numpy` library to find the functions to convert the angles from degrees to radians and calculate the sine and cosine._

---

`Numpy` nos permite también aplicar funciones matemáticas. 

Calcule el seno y el coseno de los angulos: 0, 30, 45, 60 y 90 dados en grados:
1. Cree un array con los ángulos mencionados en grados.
2. Convierta los ángulos a radianes.
3. Calcule el seno y el coseno de estos ángulos y guárdelos en dos arrays diferentes.

_Investigue la libreria `numpy` para encontrar las funciones que permitan convertir los ángulos en grados a radianes y calcular el seno y coseno._

In [ ]:
# Solution

angulos_deg = np.array([0, 30, 45, 60, 90])
angulos_rad = np.radians(angulos_deg)
cosenos = np.cos(angulos_rad)
senos = np.sin(angulos_rad)

## Pandas


[Pandas](https://pandas.pydata.org/) is a widely-used Python library for statistics, particularly on tabular data.
It borrows many features from R’s dataframes and It is posible to read a Comma Separated Values (CSV) data file.
So, pandas library provides tools to create, import and edit dataframes within python

----

[Pandas] (https://pandas.pydata.org/) es una biblioteca de Python ampliamente utilizada para estadísticas, particularmente en datos tabulares.
Toma prestadas muchas características de los marcos de datos de R y es posible leer un archivo de datos de valores separados por comas (CSV).
Entonces, la biblioteca de pandas proporciona herramientas para crear, importar y editar marcos de datos dentro de Python

To import the pandas library / Para importar la libreria de pandas:

In [29]:
import pandas as pd

### Create data / Creando datos

One way to create a dataframe is through a _dictionary_ / Una forma de crear un marco de datos es a través de un diccionario.

In [32]:
diccionario_geolatinas = {
    "Rocío": ["Soy Peruana", "Vivo en USA."], 
    "Clara": ["Soy venezolana", "Vivo en UK."],
    "Mara": ["Soy Argentina", "Vivo en Brasil"]  
}

print(diccionario_geolatinas)

{'Rocío': ['Soy Peruana', 'Vivo en USA.'], 'Clara': ['Soy venezolana', 'Vivo en UK.'], 'Mara': ['Soy Argentina', 'Vivo en Brasil']}


In [33]:
pd.DataFrame(diccionario_geolatinas )


Rocío           Clara            Mara
0   Soy Peruana  Soy venezolana   Soy Argentina
1  Vivo en USA.     Vivo en UK.  Vivo en Brasil

In [37]:
pd.DataFrame(
    diccionario_geolatinas,
    index=["Paìs de origen", "Lugar de residencia"]
)

Rocío           Clara            Mara
Paìs de origen        Soy Peruana  Soy venezolana   Soy Argentina
Lugar de residencia  Vivo en USA.     Vivo en UK.  Vivo en Brasil

### Reading data files /

We are going to work with data in a .csv file. 
` pd.read_csv()` function allows us to load the file.

----

Vamos a trabajar con datos que estan en un archivo .csv.
La función ` pd.read_csv()` permite abrir el archivo.

In [48]:
wine_reviews_file = "data/winemag-data-130k-v2.csv"
wine_reviews = pd.read_csv(wine_reviews_file)

We use the shape attribute to know how big the DataFrame is / Usamos el atributo shape para saber que tan grande es el DataFrame:

In [49]:
wine_reviews.shape

(129971, 14)

We use the `head` attribute to know how big the DataFrame is / Usamos el atributo `head` para saber que tan grande es el DataFrame:

In [50]:
wine_reviews.head(10)

Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...   
1           1  Portugal  This is ripe and fruity, a wine that is smooth...   
2           2        US  Tart and snappy, the flavors of lime flesh and...   
3           3        US  Pineapple rind, lemon pith and orange blossom ...   
4           4        US  Much like the regular bottling from 2012, this...   
5           5     Spain  Blackberry and raspberry aromas show a typical...   
6           6     Italy  Here's a bright, informal red that opens with ...   
7           7    France  This dry and restrained wine offers spice in p...   
8           8   Germany  Savory dried thyme notes accent sunnier flavor...   
9           9    France  This has great depth of flavor with its fresh ...   

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia   
1                            Avidagos      87   15.0              Douro   
2                                 NaN      87   14.0             Oregon   
3                Reserve Late Harvest      87   13.0           Michigan   
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon   
5                        Ars In Vitro      87   15.0     Northern Spain   
6                             Belsito      87   16.0  Sicily & Sardinia   
7                                 NaN      87   24.0             Alsace   
8                               Shine      87   12.0        Rheinhessen   
9                         Les Natures      87   27.0             Alsace   

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe   
1                  NaN                NaN          Roger Voss   
2    Willamette Valley  Willamette Valley        Paul Gregutt   
3  Lake Michigan Shore                NaN  Alexander Peartree   
4    Willamette Valley  Willamette Valley        Paul Gregutt   
5              Navarra                NaN   Michael Schachner   
6             Vittoria                NaN       Kerin O’Keefe   
7               Alsace                NaN          Roger Voss   
8                  NaN                NaN  Anna Lee C. Iijima   
9               Alsace                NaN          Roger Voss   

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)   
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)   
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)   
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...   
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...   
5           @wineschach  Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...   
6          @kerinokeefe   Terre di Giurfo 2013 Belsito Frappato (Vittoria)   
7            @vossroger              Trimbach 2012 Gewurztraminer (Alsace)   
8                   NaN  Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...   
9            @vossroger  Jean-Baptiste Adam 2012 Les Natures Pinot Gris...   

              variety               winery  
0         White Blend              Nicosia  
1      Portuguese Red  Quinta dos Avidagos  
2          Pinot Gris            Rainstorm  
3            Riesling           St. Julian  
4          Pinot Noir         Sweet Cheeks  
5  Tempranillo-Merlot               Tandem  
6            Frappato      Terre di Giurfo  
7      Gewürztraminer             Trimbach  
8      Gewürztraminer          Heinz Eifel  
9          Pinot Gris   Jean-Baptiste Adam