# Python Libraries / Librerias de Python

One of the advantages of using Python to process data is the ability to use libraries.
Libraries are **collections of modules** that contain functions to be used by other programs (for example, our notebooks and scripts). 
These functions usually save us a lot of time when performing certain tasks, since we do not need to write our own code to carry them out.

In addition, libraries are usually developed following best practices:
* Well designed code.
* They use version drivers.
* They have automated tests.
* Extensive documentation.
* Developed by a community.

----

Una de las ventajas de usar Python para procesar datos es la posibilidad de usar librerías. 
Las librerías son **colecciones de módulos** que contienen funciones para ser usadas por otros programas (por ejemplo, nuestros notebooks y scripts).
Estas funciones suelen ahorrarnos mucho tiempo a la hora de realizar determinadas tareas, ya que no necesitamos escribir nuestro propio código para llevarlas a cabo.

Además, las librerías suelen están desarrolladas siguiendo las mejores prácticas:
* Código bien diseñado.
* Utilizan controladores de versiones.
* Poseen testeos automatizados.
* Documentación extensiva.
* Desarrolladas por una comunidad.

## Numpy

[Numpy](https://numpy.org/) is one of the most used libraries when it comes to scientific computing. 

----

[Numpy](https://numpy.org/) es una de las librerías más utilizadas a la hora de realizar computación científica.

### Importing Numpy

In order to make use of the libraries, we first need to import them.

----

Para poder hacer uso de las librerías, primero necesitamos importarlas.

In [2]:
import numpy

This allows us to access the modules and functions of the library. 
For example, Numpy offers us a function to calculate the mean of a series of values:

---

Esto nos permite acceder a los módulos y funciones de la librería. 
Por ejemplo, Numpy nos ofrece una función para calcular la media de una serie de valores:

In [3]:
numpy.mean([1, 2, 3, 4])

2.5

Many times it is tedious to write the entire library name every time we want to use its functions or modules. 
One option is to import them under an alias. 
For example, NumPy is usually imported under the name `np`.

----

Muchas veces resulta tedioso escribir todo el nombre de la librería cada vez que queremos usar sus funciones o módulos. 
Una opción es importarlas bajo un alias. 
Por ejemplo, NumPy se suele importar bajo el nombre `np`.

In [4]:
import numpy as np

np.mean([1, 2, 3, 4])

2.5

### Numpy Arrays

NumPy introduces a new type of variable, the `numpy.array`.

Like lists, they allow you to store many values under a single variable:

---

NumPy introduce un nuevo tipo de variable, los `numpy.arrays` (o arreglos, en español).

Al igual que las listas, permiten guardar muchos valores bajo una única variable:

In [6]:
evens = np.array([2, 4, 6, 8])
print(evens)
type(evens)

[2 4 6 8]


numpy.ndarray

In [7]:
temperature = np.array([10.1, 14.6, 18.3, 20.3])
print(temperature)

[10.1 14.6 18.3 20.3]


We can use indexes as we did with lists / Podemos usar los índices como lo hacíamos con las listas:

In [8]:
temperature[0]

10.1

In [9]:
temperature[2:]

array([18.3, 20.3])

**What are the advantages and disadvantages of using `arrays`?**

* Arrays have a fixed size. Once created, we cannot add or remove values from it.
* Arrays store a single type of variables (floats or ints).
* They have a more efficient management of memory.
* All the operations we perform with _NumPy_ are faster than using _forloops_ and _lists_.

----

**¿Cuáles son las ventajas y desventajas de usar `arrays`?**

* Los arrays tienen tamaño fijo. Una vez creados, no le podemos agregar o quitar valores.
* Los arrays almacenan un único tipo de variables (floats o ints).
* Tienen un manejo mas eficiente de la memoria.
* Todas las operaciones que realicemos con _NumPy_ son más rápidas que usar _forloops_ y _lists_.


### Some Numpy functions / Algunas funciones de Numpy

Every time we make use of the functions of a library, it is advisable to read its documentation.

---

Cada vez que hagamos uso de las funciones de una librería, es recomendable leer su documentación.

In [16]:
print(temperature)

print(
    "Mean:", np.mean(temperature),
    "Standard deviation:", np.std(temperature),
    "Max:", np.max(temperature),
    "Min:", np.min(temperature)
     )

[10.1 14.6 18.3 20.3]
Mean: 15.825 Standard deviation: 3.886756359742659 Max: 20.3 Min: 10.1


### First Exercise

Using the temperature array above, index values to only include 10.1, 14.6 and 18.3.

In [ ]:
temperature[0:3]

array([10.1, 14.6, 18.3])

Note, we can also do mathematical operations on arrays. For example we can convert arrays from inches to centimeters:

In [ ]:
inches = [1,2,3,4,5,6,7]
inches = np.array(inches)
centimeters = inches * 2.54 #2.54 centimeters per inch
print(centimeters)

[ 2.54  5.08  7.62 10.16 12.7  15.24 17.78]


## Libraries: Pandas
Tha pandas library provides tools to create, import and edit dataframes within python. In this exercise, we will be going over how to create and store a dataframe. One way to create a dataframe is through a dictionary. Before we create the dataframe, we need to import the pandas package: 


In [ ]:
import pandas as pd

In [ ]:
Dictionary_Example = {'First Column': [1,2,3,4,5], 'Second Column': [10,11,12,13,14]}
df=pd.DataFrame(Dictionary_Example)
print(df)

   First Column  Second Column
0             1             10
1             2             11
2             3             12
3             4             13
4             5             14


## For pandas, should we import a da